import type { Metadata } from "next";
import "./globals.css";
import NavbarComponent from "@/components/common/NavBar";
import { inter } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Magnimont",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased overflow-x-hidden ${inter.className}`}>
        <div className="absolute w-screen z-50 top-0 left-0">
          <NavbarComponent />
        </div>
        {children}
      </body>
    </html>
  );
}
